name: Build CLI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./translator-cli
    steps:
      - uses: actions/checkout@v2
      - name: Cargo cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ./translator-cli/target
          key: test-cargo-registry
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose
  x86_64-unknown-linux-gnu:
    name: x86_64-unknown-linux-gnu
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./translator-cli
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - name: Cargo cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ./translator-cli/target
          key: build-cargo-registry-x86_64-unknown-linux-gnu
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target x86_64-unknown-linux-gnu
  x86_64-unknown-linux-musl:
    name: x86_64-unknown-linux-musl
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./translator-cli
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true
      - name: Cargo cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ./translator-cli/target
          key: build-cargo-registry-x86_64-unknown-linux-musl
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target x86_64-unknown-linux-musl

  aarch64-unknown-linux-gnu:
    name: aarch64-unknown-linux-gnu
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./translator-cli
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-gnu
          override: true
      - name: Cargo cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ./translator-cli/target
          key: build-cargo-registry-aarch64-unknown-linux-gnu
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target aarch64-unknown-linux-gnu

  aarch64-unknown-linux-musl:
    name: aarch64-unknown-linux-musl
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./translator-cli
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-musl
          override: true
      - name: Cargo cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ./translator-cli/target
          key: build-cargo-registry-aarch64-unknown-linux-musl
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target aarch64-unknown-linux-musl

  arm-unknown-linux-gnueabihf:
    name: arm-unknown-linux-gnueabihf
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./translator-cli
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: arm-unknown-linux-gnueabihf
          override: true
      - name: Cargo cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ./translator-cli/target
          key: build-cargo-registry-arm-unknown-linux-gnueabihf
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target arm-unknown-linux-gnueabihf

  arm-unknown-linux-musleabihf:
    name: arm-unknown-linux-musleabihf
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./translator-cli
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: arm-unknown-linux-musleabihf
          override: true
      - name: Cargo cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ./translator-cli/target
          key: build-cargo-registry-arm-unknown-linux-musleabihf
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target arm-unknown-linux-musleabihf

  x86_64-apple-darwin:
    name: x86_64-apple-darwin
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./translator-cli
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          override: true
      - name: Cargo cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ./translator-cli/target
          key: build-cargo-reg-x86_64-apple-darwinistry
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target x86_64-apple-darwin

  x86_64-pc-windows-gnu:
    name: x86_64-pc-windows-gnu
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./translator-cli
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
          override: true
      - name: Cargo cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ./translator-cli/target
          key: build-cargo-regis-x86_64-pc-windows-gnu
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target x86_64-pc-windows-gnu

  prepare:
    name: others
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./translator-cli
    steps:
      - name: List target
        run: find ./translator-cli/target
      - name: Compress
        run: |
          mkdir -p ./artifacts
          if [[ $OS =~ ^windows.*$ ]]; then
              EXEC=$NAME.exe
          else
              EXEC=$NAME
          fi
          if [[ $GITHUB_REF_TYPE =~ ^tag$ ]]; then
            TAG=$GITHUB_REF_NAME
          else
            TAG=$GITHUB_SHA
          fi
          mv ./translator-cli/target/$TARGET/release/$EXEC ./$EXEC
          tar -czf ./artifacts/$NAME-$TARGET-$TAG.tar.gz $EXEC
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: result
          path: |
            ./artifacts

  release:
    name: Release
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./translator-cli
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: result
          path: ./artifacts
      - name: List
        run: find ./artifacts
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/*.tar.gz